function [testPoints1,testPoints2] = CheckMapping(image1,image2,map,points)
testPoints2 = floor(repmat(size(image1),points,1).*rand(points,2));
testPoints1 = testPoints2+repmat(map-size(image1),points,1);
displaySize = [8,8];
for     p = 1:points
    image1(testPoints1(p,1):testPoints1(p,1)+displaySize(1),...
            testPoints1(p,2):testPoints1(p,2)+displaySize(2)) =...
            uint16(2^16);
    image1(testPoints1(p,1)+displaySize(1)/4:...
            testPoints1(p,1)+3*displaySize(1)/4,...
            testPoints1(p,2)+displaySize(2)/4:...
            testPoints1(p,2)+3*displaySize(2)/4) =...
            uint16(0);
    image2(testPoints2(p,1):testPoints2(p,1)+displaySize(1),...
            testPoints2(p,2):testPoints2(p,2)+displaySize(2)) =...
            uint16(2^16);
    image2(testPoints2(p,1)+displaySize(1)/4:...
            testPoints2(p,1)+3*displaySize(1)/4,...
            testPoints2(p,2)+displaySize(2)/4:...
            testPoints2(p,2)+3*displaySize(2)/4) =...
            uint16(0);
end
imshow([image1,uint16(zeros(size(image1,1),1)),image2])